### ISSUE TITLE
Password

### ISSUE THREAD

**Issue by stashenko** [KoolKid-Development/KoolLauncherV2#3]
During authorization, the nickname is checked through the database, but you can write any password. So any player can enter the server under a different nickname or nickname of the administrator

**Comment by ItzKoolKid96** [comment]
Hiii, i know about that problem here is a list whit the problems that are getting fixed in the next version:
- Login Exploit (FIXED)
- Bypass password (FIXED)
- Database files leak (FIXED)
- Admin Page XPloit (NOT FIXED WORKING ON ANOTHER APP FOR THE ADMINS)
You can join our discord to see the upcoming announcement whit the bug fix and etc:
https://kool-kid.xyz/discord

**Comment by ItzKoolKid96** [comment]
Fixed my friend enjoy!
